version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '09:00'
    open-pull-requests-limit: 5
    groups:
      dev-dependencies:
        dependency-type: development
      production-dependencies:
        dependency-type: production
    labels:
      - dependencies
      - automated
    ignore:
      - dependency-name: ink
        update-types: ['version-update:semver-major']
      - dependency-name: typescript
        update-types: ['version-update:semver-major']
