// src/cli/format-verify.ts
// CLI formatters for the verify-gate output. All functions return
// RenderedLine[] so the caller (REPL Ink renderer, one-shot stdout writer,
// JSON serializer) picks how to realize the color hint.

import * as path from 'node:path';
import type { GateResult, VerificationResult, RefactorPlan } from '../contracts.js';
import { theme } from '../ui/theme.js';
import type { RenderedLine } from './format-types.js';

export type GateName = 'syntax' | 'imports' | 'tests';

const GATE_ORDER: GateName[] = ['syntax', 'imports', 'tests'];

function formatDuration(ms: number): string {
  if (ms < 1000) return `${ms}ms`;
  return `${(ms / 1000).toFixed(1)}s`;
}

function gateIndex(gate: GateName): number {
  return GATE_ORDER.indexOf(gate) + 1;
}

export function formatGateProgress(gate: GateName, result: GateResult): RenderedLine[] {
  const symbol = result.passed ? theme.symbols.pass : theme.symbols.fail;
  const color = result.passed ? theme.colors.success : theme.colors.error;
  const namePadded = gate.padEnd(8);
  const text = `  ${symbol}  Gate ${gateIndex(gate)} / ${GATE_ORDER.length}   ${namePadded}  ${formatDuration(result.durationMs)}`;
  return [{ text, color }];
}

export function formatVerifySuccess(
  result: VerificationResult,
  _plan: RefactorPlan,
  projectRoot: string,
): RenderedLine[] {
  const out: RenderedLine[] = [];
  out.push({ text: '', color: theme.colors.text });
  out.push({ text: '  Atomic write:', color: theme.colors.accent });
  for (const c of result.writableChanges) {
    const rel = path.relative(projectRoot, c.path) || c.path;
    const padded = rel.padEnd(48);
    out.push({
      text: `    ${theme.symbols.pass} ${padded} [${c.transformId}]`,
      color: theme.colors.text,
    });
  }
  out.push({ text: '', color: theme.colors.text });
  out.push({
    text: `  ${theme.symbols.pass} ${result.writableChanges.length} file(s) refactored and verified.`,
    color: theme.colors.success,
  });
  out.push({
    text: '  Run `document` to generate docstrings + CHANGELOG.',
    color: theme.colors.textDim,
  });
  out.push({ text: '', color: theme.colors.text });
  return out;
}

/**
 * Pulls the structured "Failing tests:" block out of a blockingReason
 * generated by `summarizeVitestFailures`. The block lives between the
 * "Failing tests:" header and the "Raw tail:" marker. Returns null if the
 * structured block isn't present (the gate didn't have any vitest failures).
 */
function extractFailingTestsBlock(blockingReason: string | undefined): string[] | null {
  if (!blockingReason) return null;
  const startIdx = blockingReason.indexOf('Failing tests:');
  if (startIdx < 0) return null;
  const rest = blockingReason.slice(startIdx + 'Failing tests:'.length);
  const endIdx = rest.indexOf('Raw tail:');
  const block = endIdx >= 0 ? rest.slice(0, endIdx) : rest;
  return block
    .split('\n')
    .map((l) => l.replace(/\s+$/u, ''))
    .filter((l) => l.length > 0);
}

function findFailedGate(result: VerificationResult): GateName | null {
  for (const g of GATE_ORDER) {
    if (!result.gates[g].passed) return g;
  }
  return null;
}

function stripKnownExt(base: string): string {
  return base.replace(/\.(?:py|tsx|ts|jsx|js)$/u, '');
}

function pickCulprit(
  plan: RefactorPlan,
  blockingReason: string | undefined,
): { transformId: string; relPath: string } | null {
  if (!blockingReason) return null;
  for (const c of plan.changes) {
    const base = stripKnownExt(path.basename(c.path));
    if (base.length === 0) continue;
    if (blockingReason.includes(base)) {
      return { transformId: c.transformId, relPath: c.path };
    }
  }
  return null;
}

export function formatVerifyFailure(
  result: VerificationResult,
  plan: RefactorPlan,
  projectRoot: string,
  shadowRoot: string | null,
): RenderedLine[] {
  const out: RenderedLine[] = [];
  const failed = findFailedGate(result);
  const failedName = failed ?? 'unknown';
  const failedGate = failed !== null ? result.gates[failed] : undefined;

  out.push({ text: '', color: theme.colors.text });
  out.push({
    text: `  ${theme.symbols.fail} Verification failed at gate '${failedName}'.`,
    color: theme.colors.error,
  });

  // Section 2: failing tests block (if present in blockingReason).
  const block = extractFailingTestsBlock(failedGate?.blockingReason);
  if (block !== null && block.length > 0) {
    out.push({ text: '', color: theme.colors.text });
    out.push({ text: '  Failing tests:', color: theme.colors.error });
    for (const line of block) {
      out.push({ text: `    ${line}`, color: theme.colors.text });
    }
  } else if (failedGate?.blockingReason) {
    // No structured block — render the raw blockingReason indented.
    out.push({ text: '', color: theme.colors.text });
    for (const line of failedGate.blockingReason.split('\n')) {
      out.push({ text: `    ${line}`, color: theme.colors.textDim });
    }
  }

  // Section 3: in-flight plan summary.
  out.push({ text: '', color: theme.colors.text });
  out.push({
    text: '  Proposed changes (NOT written — your tree is unchanged):',
    color: theme.colors.warning,
  });
  for (const c of plan.changes) {
    const rel = path.relative(projectRoot, c.path) || c.path;
    out.push({
      text: `    ${theme.symbols.bullet} ${rel} [${c.transformId}]`,
      color: theme.colors.textDim,
    });
  }

  // Section 4: reproduce hint.
  if (shadowRoot !== null && shadowRoot.length > 0) {
    out.push({ text: '', color: theme.colors.text });
    out.push({ text: '  To reproduce locally:', color: theme.colors.accent });
    out.push({
      text: `    cd ${shadowRoot} && npx vitest run`,
      color: theme.colors.text,
    });
  }

  // Section 5: culprit hint (best-effort match by basename).
  const culprit = pickCulprit(plan, failedGate?.blockingReason);
  if (culprit !== null) {
    const rel = path.relative(projectRoot, culprit.relPath) || culprit.relPath;
    out.push({ text: '', color: theme.colors.text });
    out.push({
      text: `  Likely culprit: the \`${culprit.transformId}\` transform on \`${rel}\`.`,
      color: theme.colors.warning,
    });
  }

  out.push({ text: '', color: theme.colors.text });
  return out;
}
